/**
 * PdfGenerator
 * Converts report data objects to A4-optimised HTML that expo-print renders to PDF.
 * No external PDF library needed — expo-print handles rendering.
 * Extensible: future cloud PDF service can receive the same HTML string.
 */

import {
  FinancialReport,
  CashFlowReport,
  CustomerReport,
  LedgerReport,
  ProfitLossReport,
  ReminderReport,
  ReportMeta,
  TransactionRow,
} from './reportsRepository';

// ─── Shared HTML helpers ─────────────────────────────────────────────────────

const currency = (n: number): string =>
  `₹${Math.abs(n).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

const badge = (text: string, color: string) =>
  `<span style="background:${color};color:#fff;padding:2px 8px;border-radius:12px;font-size:11px">${text}</span>`;

const metaHtml = (meta: ReportMeta) => `
  <div class="meta">
    <div class="meta-left">
      <div class="report-title">${meta.title}</div>
      <div class="report-sub">Period: ${meta.dateFilter.from.toLocaleDateString()} – ${meta.dateFilter.to.toLocaleDateString()}</div>
      <div class="report-sub">Generated: ${meta.generatedAt.toLocaleString()}</div>
    </div>
    <div class="logo">🏢</div>
  </div>`;

const kpiCard = (label: string, value: string, color = '#6366f1') =>
  `<div class="kpi"><div class="kpi-value" style="color:${color}">${value}</div><div class="kpi-label">${label}</div></div>`;

const txTableHtml = (rows: TransactionRow[], title = 'Transactions') => {
  if (rows.length === 0) return `<p style="color:#888">No transactions in selected period.</p>`;
  const trs = rows.map((r) => `
    <tr>
      <td>${r.date.toLocaleDateString()}</td>
      <td>${badge(r.type, r.type === 'INCOME' || r.type === 'GOT' ? '#22c55e' : '#ef4444')}</td>
      <td>${r.ledgerName}</td>
      <td>${r.categoryName}</td>
      <td class="${r.type === 'INCOME' || r.type === 'GOT' ? 'credit' : 'debit'}">${currency(r.amount)}</td>
      <td>${r.note}</td>
    </tr>`).join('');

  return `
    <h3>${title}</h3>
    <table>
      <thead><tr><th>Date</th><th>Type</th><th>Ledger</th><th>Category</th><th>Amount</th><th>Note</th></tr></thead>
      <tbody>${trs}</tbody>
    </table>`;
};

const baseHtml = (title: string, body: string) => `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>${title}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; font-size: 12px; color: #1f2937; padding: 24px 32px; }
  .meta { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
  .report-title { font-size: 22px; font-weight: 700; color: #111; }
  .report-sub { color: #6b7280; font-size: 11px; margin-top: 4px; }
  .logo { font-size: 40px; }
  .kpi-grid { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 24px; }
  .kpi { background: #f9fafb; border-radius: 10px; padding: 14px 18px; min-width: 140px; border: 1px solid #e5e7eb; }
  .kpi-value { font-size: 20px; font-weight: 700; }
  .kpi-label { color: #6b7280; font-size: 10px; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th { background: #6366f1; color: #fff; text-align: left; padding: 8px 10px; font-size: 11px; }
  td { border-bottom: 1px solid #f0f0f0; padding: 7px 10px; font-size: 11px; }
  tr:nth-child(even) { background: #f9fafb; }
  h3 { font-size: 14px; color: #1f2937; margin-bottom: 10px; border-left: 3px solid #6366f1; padding-left: 8px; }
  h4 { font-size: 12px; color: #6b7280; margin: 16px 0 8px 0; }
  .credit { color: #22c55e; font-weight: 700; }
  .debit  { color: #ef4444; font-weight: 700; }
  .total-row { background: #ede9fe !important; font-weight: 700; }
  .footer { margin-top: 32px; border-top: 1px solid #e5e7eb; padding-top: 12px; color: #9ca3af; font-size: 10px; text-align: center; }
  @page { size: A4; margin: 16mm; }
</style>
</head>
<body>
${body}
<div class="footer">Generated by Frincy · Confidential · Page 1</div>
</body>
</html>`;

// ─── PDF Generators ───────────────────────────────────────────────────────────

export function generateFinancialPdf(report: FinancialReport): string {
  const { meta, summary, transactions, categoryBreakdown } = report;

  const kpis = `
    <div class="kpi-grid">
      ${kpiCard('Income', currency(summary.income), '#22c55e')}
      ${kpiCard('Expense', currency(summary.expense), '#ef4444')}
      ${kpiCard(summary.profit > 0 ? 'Net Profit' : summary.profit < 0 ? 'Net Loss' : 'Break Even', currency(Math.abs(summary.profit)), summary.profit > 0 ? '#22c55e' : summary.profit < 0 ? '#ef4444' : '#9ca3af')}
      ${kpiCard('Receivable', currency(summary.totalReceivable), '#6366f1')}
      ${kpiCard('Payable', currency(summary.totalPayable), '#f59e0b')}
    </div>`;

  const catRows = categoryBreakdown.slice(0, 10).map((c) =>
    `<tr><td>${c.name}</td><td>${c.count}</td><td class="credit">${currency(c.amount)}</td></tr>`,
  ).join('');

  const catTable = categoryBreakdown.length > 0
    ? `<h3>Category Breakdown</h3>
       <table>
         <thead><tr><th>Category</th><th>Transactions</th><th>Amount</th></tr></thead>
         <tbody>${catRows}</tbody>
       </table>`
    : '';

  const body = metaHtml(meta) + kpis + catTable + txTableHtml(transactions.slice(0, 100));
  return baseHtml(meta.title, body);
}

export function generateProfitLossPdf(report: ProfitLossReport): string {
  const { meta, income, expense, netProfit, incomeByCategory, expenseByCategory } = report;

  const kpis = `
    <div class="kpi-grid">
      ${kpiCard('Total Income', currency(income), '#22c55e')}
      ${kpiCard('Total Expense', currency(expense), '#ef4444')}
      ${kpiCard(netProfit > 0 ? 'Net Profit' : netProfit < 0 ? 'Net Loss' : 'Break Even', currency(Math.abs(netProfit)), netProfit > 0 ? '#22c55e' : netProfit < 0 ? '#ef4444' : '#9ca3af')}
    </div>`;

  const incRows = incomeByCategory.map((c) =>
    `<tr><td>${c.name}</td><td>${c.count}</td><td class="credit">${currency(c.amount)}</td></tr>`,
  ).join('');
  const expRows = expenseByCategory.map((c) =>
    `<tr><td>${c.name}</td><td>${c.count}</td><td class="debit">${currency(c.amount)}</td></tr>`,
  ).join('');

  const tables = `
    <h3>Income by Category</h3>
    <table>
      <thead><tr><th>Category</th><th>Txns</th><th>Amount</th></tr></thead>
      <tbody>${incRows || '<tr><td colspan="3">No income data</td></tr>'}</tbody>
    </table>
    <h3>Expense by Category</h3>
    <table>
      <thead><tr><th>Category</th><th>Txns</th><th>Amount</th></tr></thead>
      <tbody>${expRows || '<tr><td colspan="3">No expense data</td></tr>'}</tbody>
      <tfoot><tr class="total-row"><td>${netProfit > 0 ? 'NET PROFIT' : netProfit < 0 ? 'NET LOSS' : 'BREAK EVEN'}</td><td></td><td class="${netProfit > 0 ? 'credit' : netProfit < 0 ? 'debit' : ''}">${currency(Math.abs(netProfit))}</td></tr></tfoot>
    </table>`;

  return baseHtml(meta.title, metaHtml(meta) + kpis + tables);
}

export function generateCashFlowPdf(report: CashFlowReport): string {
  const { meta, totalInflows, totalOutflows, closingBalance, rows } = report;

  const kpis = `
    <div class="kpi-grid">
      ${kpiCard('Total Inflows', currency(totalInflows), '#22c55e')}
      ${kpiCard('Total Outflows', currency(totalOutflows), '#ef4444')}
      ${kpiCard('Closing Balance', currency(closingBalance), closingBalance >= 0 ? '#22c55e' : '#ef4444')}
    </div>`;

  return baseHtml(meta.title, metaHtml(meta) + kpis + txTableHtml(rows.slice(0, 200)));
}

export function generateCustomerPdf(report: CustomerReport): string {
  const { meta, summary, rows } = report;

  const kpis = `
    <div class="kpi-grid">
      ${kpiCard('Total Customers', String(summary.total))}
      ${kpiCard('With Due', String(summary.withDue), '#ef4444')}
      ${kpiCard('With Credit', String(summary.withCredit), '#22c55e')}
      ${kpiCard('Total Receivable', currency(summary.totalReceivable), '#22c55e')}
      ${kpiCard('Total Payable', currency(summary.totalPayable), '#ef4444')}
    </div>`;

  const trs = rows.map((r) => `
    <tr>
      <td>${r.name}</td>
      <td>${r.phone}</td>
      <td>${r.email}</td>
      <td class="${r.balance >= 0 ? 'credit' : 'debit'}">${currency(r.balance)}</td>
      <td>${r.totalTransactions}</td>
      <td>${r.lastActivityDate?.toLocaleDateString() ?? '—'}</td>
    </tr>`).join('');

  const table = `
    <h3>Customer List</h3>
    <table>
      <thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Balance</th><th>Txns</th><th>Last Activity</th></tr></thead>
      <tbody>${trs || '<tr><td colspan="6">No customers</td></tr>'}</tbody>
    </table>`;

  return baseHtml(meta.title, metaHtml(meta) + kpis + table);
}

export function generateLedgerPdf(report: LedgerReport): string {
  const { meta, rows, totals } = report;

  const kpis = `
    <div class="kpi-grid">
      ${kpiCard('Total Ledgers', String(rows.length))}
      ${kpiCard('Total Income', currency(totals.totalIncome), '#22c55e')}
      ${kpiCard('Total Expense', currency(totals.totalExpense), '#ef4444')}
      ${kpiCard(totals.totalIncome - totals.totalExpense > 0 ? 'Net Profit' : totals.totalIncome - totals.totalExpense < 0 ? 'Net Loss' : 'Break Even', currency(Math.abs(totals.totalIncome - totals.totalExpense)), totals.totalIncome - totals.totalExpense > 0 ? '#22c55e' : totals.totalIncome - totals.totalExpense < 0 ? '#ef4444' : '#9ca3af')}
    </div>`;

  const trs = rows.map((r) => `
    <tr>
      <td>${r.name}</td>
      <td>${r.type}</td>
      <td class="credit">${currency(r.totalIncome)}</td>
      <td class="debit">${currency(r.totalExpense)}</td>
      <td class="${r.closingBalance >= 0 ? 'credit' : 'debit'}">${currency(r.closingBalance)}</td>
      <td>${r.transactionCount}</td>
    </tr>`).join('');

  const table = `
    <h3>Ledger Summary</h3>
    <table>
      <thead><tr><th>Ledger</th><th>Type</th><th>Income</th><th>Expense</th><th>Balance</th><th>Txns</th></tr></thead>
      <tbody>${trs || '<tr><td colspan="6">No ledgers</td></tr>'}</tbody>
      <tfoot><tr class="total-row"><td>TOTALS</td><td></td><td>${currency(totals.totalIncome)}</td><td>${currency(totals.totalExpense)}</td><td class="${totals.totalIncome - totals.totalExpense > 0 ? 'credit' : totals.totalIncome - totals.totalExpense < 0 ? 'debit' : ''}">${currency(Math.abs(totals.totalIncome - totals.totalExpense))}</td><td></td></tr></tfoot>
    </table>`;

  return baseHtml(meta.title, metaHtml(meta) + kpis + table);
}

export function generateReminderPdf(report: ReminderReport): string {
  const { meta, pending, overdue } = report;

  const renderRows = (items: typeof pending) => items.map((r) =>
    `<tr><td>${r.title}</td><td>${r.dueDate.toLocaleDateString()}</td><td>${badge(r.status, '#6366f1')}</td></tr>`,
  ).join('');

  const body = `
    ${metaHtml(meta)}
    <div class="kpi-grid">
      ${kpiCard('Pending', String(pending.length), '#6366f1')}
      ${kpiCard('Overdue', String(overdue.length), '#ef4444')}
    </div>
    <h3>Pending Reminders</h3>
    <table>
      <thead><tr><th>Title</th><th>Due Date</th><th>Status</th></tr></thead>
      <tbody>${renderRows(pending) || '<tr><td colspan="3">No pending reminders</td></tr>'}</tbody>
    </table>
    <h3>Overdue Reminders</h3>
    <table>
      <thead><tr><th>Title</th><th>Due Date</th><th>Status</th></tr></thead>
      <tbody>${renderRows(overdue) || '<tr><td colspan="3">No overdue reminders</td></tr>'}</tbody>
    </table>`;

  return baseHtml(meta.title, body);
}
