import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Customer, Transaction } from '../database/models';

export async function generateLedgerPDF(customer: Customer, transactions: Transaction[], runningBalance: number) {
  const html = `
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
          h1 { text-align: center; color: #111; }
          .header { margin-bottom: 20px; border-bottom: 2px solid #eee; padding-bottom: 10px; }
          .summary { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 18px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #f8f9fa; font-weight: bold; }
          .income { color: #22c55e; }
          .expense { color: #ef4444; }
          .balance { font-weight: bold; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Ledger Statement</h1>
          <p><strong>Customer:</strong> ${customer.name}</p>
          <p><strong>Phone:</strong> ${customer.phone || 'N/A'}</p>
        </div>
        <div class="summary">
          <span><strong>Total Transactions:</strong> ${transactions.length}</span>
          <span class="balance"><strong>Net Balance:</strong> ₹${runningBalance.toFixed(2)} ${runningBalance >= 0 ? '(Cr)' : '(Dr)'}</span>
        </div>
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Details</th>
              <th>Type</th>
              <th>Amount (₹)</th>
            </tr>
          </thead>
          <tbody>
            ${transactions.map(t => `
              <tr>
                <td>${new Date(t.date * 1000).toLocaleDateString()}</td>
                <td>${t.note || '-'}</td>
                <td class="${['INCOME', 'GOT'].includes(t.type) ? 'income' : 'expense'}">${t.type}</td>
                <td>${t.amount.toFixed(2)}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        <p style="text-align: center; margin-top: 40px; font-size: 12px; color: #888;">Generated by Frincy</p>
      </body>
    </html>
  `;

  try {
    await Print.printAsync({ html });
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
}
